# <font color='blue'>Data Science Academy - Python Fundamentos - Capítulo 8</font>

## Download: http://github.com/dsacademybr

### NumPy

Para importar numpy, utilize: 
import numpy as np

Você também pode utilizar: 
from numpy import *  .Isso evitará a utilização de np., mas este comando importará todos os módulos do NumPy

In [ ]:
# Importando o NumPy
import numpy as np

## Criando Arrays

In [ ]:
# Help
help(np.array)

In [ ]:
# Array criado a partir de uma lista:
vetor1 = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [ ]:
print(vetor1)

In [ ]:
# Um objeto do tipo ndarray é um recipiente multidimensional de itens 
# do mesmo tipo e tamanho.
type(vetor1)

In [ ]:
# Criando uma lista. Perceba como listas e arrays são objetos 
# diferentes, com diferentes propriedades
lst = [0, 1, 2, 3, 4, 5, 6, 7, 8]

In [ ]:
lst

In [ ]:
type(lst)

In [ ]:
# Imprimindo na tela um elemento específico no array
vetor1[0] 

In [ ]:
# Alterando um elemento do array
vetor1[0] = 100

In [ ]:
print(vetor1)

In [ ]:
vetor1[0] = 'Novo elemento'

In [ ]:
# Verificando o formato do array
print(vetor1.shape)

In [ ]:
# A função arange cria um vetor contendo uma progressão aritmética 
# a partir de um intervalo - start, stop, step
vetor2 = np.arange(0., 4.5, .5)

In [ ]:
print(vetor2)

In [ ]:
# Verificando o tipo do objeto
type(vetor2)

In [ ]:
# Formato do array
np.shape(vetor2)

In [ ]:
print (vetor2.dtype)

In [ ]:
x = np.arange(1, 10, 0.25)
print (x)

In [ ]:
print (np.zeros(10))

In [ ]:
# Retorna 1 nas posições em diagonal e 0 no restante
z = np.eye(3)

In [ ]:
z

In [ ]:
# Os valores passados como parâmetro, formam uma diagonal
d = np.diag(np.array([1, 2, 3, 4]))

In [ ]:
d

In [ ]:
# Array de números complexos
c = np.array([1+2j, 3+4j, 5+6*1j])

In [ ]:
c

In [ ]:
# Array de valores booleanos
b = np.array([True, False, False, True])

In [ ]:
b

In [ ]:
# Array de strings
s = np.array(['Python', 'R', 'Julia'])

In [ ]:
s

In [ ]:
# O método linspace (linearly spaced vector) retorna um número de 
# valores igualmente distribuídos no intervalo especificado 
np.linspace(0, 10)

In [ ]:
print (np.linspace(0, 10, 15))

In [ ]:
print (np.logspace(0, 5, 10))

## Criando uma Matriz

In [ ]:
# Criando uma matriz
matriz = np.array([[1,2,3],[4,5,6]]) 

In [ ]:
print(matriz)

In [ ]:
print(matriz.shape)

In [ ]:
# Criando uma matriz 2x3 apenas com números "1"
matriz1 = np.ones((2,3))

In [ ]:
print(matriz1)

In [ ]:
# Criando uma matriz a partir de uma lista de listas
lista = [[13,81,22], [0, 34, 59], [21, 48, 94]]

In [ ]:
# A função matrix cria uma matria a partir de uma sequência
matriz2 = np.matrix(lista)

In [ ]:
matriz2

In [ ]:
type(matriz2)

In [ ]:
# Formato da matriz
np.shape(matriz2)

In [ ]:
matriz2.size

In [ ]:
print(matriz2.dtype)

In [ ]:
matriz2.itemsize

In [ ]:
matriz2.nbytes

In [ ]:
print(matriz2[2,1])

In [ ]:
# Alterando um elemento da matriz
matriz2[1,0] = 100

In [ ]:
matriz2

In [ ]:
x = np.array([1, 2])  # NumPy decide o tipo dos dados
y = np.array([1.0, 2.0])  # NumPy decide o tipo dos dados
z = np.array([1, 2], dtype=np.float64)  # Forçamos um tipo dado em particular

print (x.dtype, y.dtype, z.dtype)

In [ ]:
matriz3 = np.array([[24, 76], [35, 89]], dtype=float)

In [ ]:
matriz3

In [ ]:
matriz3.itemsize

In [ ]:
matriz3.nbytes

In [ ]:
matriz3.ndim

In [ ]:
matriz3[1,1]

In [ ]:
matriz3[1,1] = 100

In [ ]:
matriz3

## Usando o método random() do NumPy

In [ ]:
print (np.random.rand(10))

In [ ]:
import matplotlib.pyplot as plt
%matplotlib inline

In [ ]:
print (np.random.rand(10))

In [ ]:
plt.show((plt.hist(np.random.rand(1000))))

In [ ]:
print (np.random.randn(5,5))

In [ ]:
plt.show(plt.hist(np.random.randn(1000)))

In [ ]:
imagem = np.random.rand(30, 30)
plt.imshow(imagem, cmap = plt.cm.hot)    
plt.colorbar()    

## Operações com datasets

In [6]:
import os
import numpy as np
filename = os.path.join('iris.csv')

In [4]:
# No Windows use !more iris.csv. Mac ou Linux use !head iris.csv
!more iris.csv

sepal_length,sepal_width,petal_length,petal_width,species
5.1,3.5,1.4,0.2,setosa
4.9,3,1.4,0.2,setosa
4.7,3.2,1.3,0.2,setosa
4.6,3.1,1.5,0.2,setosa
5,3.6,1.4,0.2,setosa
5.4,3.9,1.7,0.4,setosa
4.6,3.4,1.4,0.3,setosa
5,3.4,1.5,0.2,setosa
4.4,2.9,1.4,0.2,setosa
4.9,3.1,1.5,0.1,setosa
5.4,3.7,1.5,0.2,setosa
4.8,3.4,1.6,0.2,setosa
4.8,3,1.4,0.1,setosa
4.3,3,1.1,0.1,setosa
5.8,4,1.2,0.2,setosa
5.7,4.4,1.5,0.4,setosa
5.4,3.9,1.3,0.4,setosa
5.1,3.5,1.4,0.3,setosa
5.7,3.8,1.7,0.3,setosa
5.1,3.8,1.5,0.3,setosa
5.4,3.4,1.7,0.2,setosa
5.1,3.7,1.5,0.4,setosa
m--More--(14%)

In [7]:
# Carregando um dataset para dentro de um array
arquivo = np.loadtxt(filename, delimiter=',', usecols=(0,1,2,3), skiprows=1)
print (arquivo)

[[ 5.1  3.5  1.4  0.2]
 [ 4.9  3.   1.4  0.2]
 [ 4.7  3.2  1.3  0.2]
 [ 4.6  3.1  1.5  0.2]
 [ 5.   3.6  1.4  0.2]
 [ 5.4  3.9  1.7  0.4]
 [ 4.6  3.4  1.4  0.3]
 [ 5.   3.4  1.5  0.2]
 [ 4.4  2.9  1.4  0.2]
 [ 4.9  3.1  1.5  0.1]
 [ 5.4  3.7  1.5  0.2]
 [ 4.8  3.4  1.6  0.2]
 [ 4.8  3.   1.4  0.1]
 [ 4.3  3.   1.1  0.1]
 [ 5.8  4.   1.2  0.2]
 [ 5.7  4.4  1.5  0.4]
 [ 5.4  3.9  1.3  0.4]
 [ 5.1  3.5  1.4  0.3]
 [ 5.7  3.8  1.7  0.3]
 [ 5.1  3.8  1.5  0.3]
 [ 5.4  3.4  1.7  0.2]
 [ 5.1  3.7  1.5  0.4]
 [ 4.6  3.6  1.   0.2]
 [ 5.1  3.3  1.7  0.5]
 [ 4.8  3.4  1.9  0.2]
 [ 5.   3.   1.6  0.2]
 [ 5.   3.4  1.6  0.4]
 [ 5.2  3.5  1.5  0.2]
 [ 5.2  3.4  1.4  0.2]
 [ 4.7  3.2  1.6  0.2]
 [ 4.8  3.1  1.6  0.2]
 [ 5.4  3.4  1.5  0.4]
 [ 5.2  4.1  1.5  0.1]
 [ 5.5  4.2  1.4  0.2]
 [ 4.9  3.1  1.5  0.1]
 [ 5.   3.2  1.2  0.2]
 [ 5.5  3.5  1.3  0.2]
 [ 4.9  3.1  1.5  0.1]
 [ 4.4  3.   1.3  0.2]
 [ 5.1  3.4  1.5  0.2]
 [ 5.   3.5  1.3  0.3]
 [ 4.5  2.3  1.3  0.3]
 [ 4.4  3.2  1.3  0.2]
 [ 5.   3.5

In [8]:
type(arquivo)

numpy.ndarray

In [ ]:
# Gerando um plot a partir de um arquivo usando o NumPy
var1, var2 = np.loadtxt(filename, delimiter=',', usecols=(0,1), skiprows=1, unpack=True)
plt.show(plt.plot(var1, var2, 'o', markersize=8, alpha=0.75))

## Estatística

In [ ]:
# Criando um array
A = np.array([15, 23, 63, 94, 75])

In [ ]:
# Em estatística a média é o valor que aponta para onde mais se 
# concentram os dados de uma distribuição.
np.mean(A)

In [ ]:
# O desvio padrão mostra o quanto de variação ou "dispersão" existe em 
# relação à média (ou valor esperado). 
# Um baixo desvio padrão indica que os dados tendem a estar próximos da 
# média; 
# Um desvio padrão alto indica que os dados estão espalhados por uma gama 
# de valores
np.std(A)

In [ ]:
# Variância de uma variável aleatória é uma medida da sua dispersão 
# estatística, indicando "o quão longe" em geral os seus valores se 
# encontram do valor esperado
np.var(A)

In [ ]:
d = np.arange(1, 10)

In [ ]:
d

In [ ]:
np.sum(d)

In [ ]:
# Retorna o produto dos elementos
np.prod(d)

In [ ]:
# Soma acumulada dos elementos
np.cumsum(d)

In [ ]:
a = np.random.randn(400,2)
m = a.mean(0)
print (m, m.shape)

In [ ]:
plt.plot(a[:,0], a[:,1], 'o', markersize=5, alpha=0.50)
plt.plot(m[0], m[1], 'ro', markersize=10)
plt.show()

## Outras operações com arrays

In [ ]:
# Slicing
a = np.diag(np.arange(3))

In [ ]:
a

In [ ]:
a[1, 1]

In [ ]:
a[1]

In [ ]:
b = np.arange(10)

In [ ]:
b

In [ ]:
# [start:end:step]
b[2:9:3] 

In [ ]:
# Comparação
a = np.array([1, 2, 3, 4])
b = np.array([4, 2, 2, 4])
a == b

In [ ]:
np.array_equal(a, b)

In [ ]:
a.min()

In [ ]:
a.max()

In [ ]:
# Somando um elemento ao array
np.array([1, 2, 3]) + 1.5

In [ ]:
# Usando o método around
a = np.array([1.2, 1.5, 1.6, 2.5, 3.5, 4.5])

In [ ]:
b = np.around(a)

In [ ]:
b

In [ ]:
# Criando um array
B = np.array([1, 2, 3, 4])

In [ ]:
B

In [ ]:
# Copiando um array
C = B.flatten()

In [ ]:
C

In [ ]:
# Criando um array
v = np.array([1, 2, 3])

In [ ]:
# Adcionando uma dimensão ao array
v[:, np.newaxis], v[:,np.newaxis].shape, v[np.newaxis,:].shape

In [ ]:
# Repetindo os elementos de um array
np.repeat(v, 3)

In [ ]:
# Repetindo os elementos de um array
np.tile(v, 3)

In [ ]:
# Criando um array
w = np.array([5, 6])

In [ ]:
# Concatenando
np.concatenate((v, w), axis=0)

In [ ]:
# Copiando arrays
r = np.copy(v)

In [ ]:
r

# Fim

### Obrigado - Data Science Academy - <a href=http://facebook.com/dsacademy>facebook.com/dsacademybr</a>